version: "3.4"
services:
  database:
    image: mysql:latest
    environment:
      - "MYSQL_ROOT_PASSWORD=geheim"
      - "MYSQL_DATABASE=termine2"
      - TZ=Europe/Berlin
  termine2:
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - "database"