version: "3.4"
services:
  database:
    image: mysql:latest
    volumes:
      - ./mysql/db/entrypoint:/docker-entrypoint-initdb.d/
      - ./mysql/db/config.cnf:/etc/mysql/conf.d/config.cnf
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=geheim"
      - "MYSQL_DATABASE=termine2"
  termine2:
    build: ./
    ports:
      - "8080:8080"