= Management Summary

== Problemstatement:
Es gibt in der Universität keine Plattform zur Terminfindung
und die Funktion von Umfragen in ILIAS ist nur für Organisatoren verfügbar.
Außerdem dauert es lange, sich im ILIAS durchzunavigieren. 
Weiter sind Abstimmungen und Termine nicht in einem System der Universität integriert und es sind Zugriffe 
auf externe Dienste notwendig. 
Es gibt keine klare Übersicht der Termine und Umfragen. 
Kopieren von Umfragen ist äußerst umständlich.

== Ziele & Features:
Mit einem Klick auf die Sidebar auf der MOPS Startseite erreicht man die Übersicht der Terminfindung, 
wo entweder alle Terminabstimmungen (offene und fertige), welche für Mitglieder der jeweiligen Gruppen sichtbar sind, 
oder die Terminabstimmungen, welchen der Nutzer per Link beigetreten ist, angezeigt werden.
Dadurch ist es schnell und praktisch, Gruppentreffen zu organisieren.

Zusätzlich dazu gibt es eine Seite für generelle Abstimmungen bzw. Umfragen, die auch erreichbar ist.
Das Erstellen von Terminen und Umfragen ist schnell und intuitiv.

Die Gruppen, welche in einem anderen System erstellt werden können, können für die Abstimmungen direkt verwendet werden.
Alternativ ist auch ein Zugang über Link möglich, sodass Abstimmungen unabhängig von Gruppen sein können.

Import und Export von Terminabstimmungen/Umfragen ermöglicht einfaches Kopieren der Daten.

Sowohl Termine und Umfragen, als auch die Antworten können im Nachhinein noch geändert werden.
Das Ergebnis einer Abstimmung liefert beispielsweise einen Termin, 
an welchem sich eine Gruppe treffen kann, wo die meisten Mitglieder Zeit haben.

Das Web-Element der Umfrage ist für bessere Übersicht, entsprechend den Entscheidungsmöglichkeiten, gefärbt.
Die Farben sind so gewählt, dass sich Menschen mit Sehschwäche beser damit zurechtfinden.

== Hinweise:
=== Arc42 und Dokumentation
Beide liegen im Ordner "arc42" im Hauptverzeichnis.

Die Produktions-Version muss mit

`docker-compose -f docker-compose-prod.yml up --build`

gestartet werden.

=== Pfade
==== Termine
[cols="1,1" options="header"]
|===
| Beschreibung | Pfad
| Übersicht über alle verfügbaren Termine | /termine2
| Neue Terminfindung erstellen | /termine2/termine-neu
| Abstimmen | /termine2/{linkId}/abstimmung
| Ergebnis | /termine2/{linkId}/ergebnis
|===

==== Umfragen
[cols="1,1" options="header"]
|===
| Beschreibung | Pfad
| Übersicht über alle verfügbaren Umfragen | /termine2/umfragen
| Neue Umfrage erstellen | /termine2/umfragen-neu
| Abstimmen | /termine2/umfragen/{linkId}}/abstimmung
| Ergebnis | /termine2/umfragen/{linkId}}/ergebnis
|===
