[[section-introduction-and-goals]]
==	Einführung und Ziele

[role="arc42help"]
****
Beschreibt die wesentlichen Anforderungen und treibenden Kräfte, die bei der Umsetzung der Softwarearchitektur und Entwicklung des Systems berücksichtigt werden müssen.

Dazu gehören:

* zugrunde liegende Geschäftsziele,
* wesentliche Aufgabenstellungen und
* essenzielle fachliche Anforderungen an das System sowie
* Qualitätsziele für die Architektur und
* relevante Stakeholder und deren Erwartungshaltung.
****

Mit einem Klick auf die Sidebar auf der MOPS Startseite erreicht man die Übersicht der Terminfindung, wo entweder alle Terminabstimmungen (offene und fertige), welche für Mitglieder der jeweiligen Gruppen sichtbar sind, oder die Terminabstimmungen, welchen der Nutzer per Link beigetreten ist, angezeigt werden. Dadurch ist es schnell und praktisch, Gruppentreffen zu organisieren.

Zusätzlich dazu gibt es eine Seite für generelle Abstimmungen bzw. Umfragen, die auch erreichbar ist. Das Erstellen von Terminen und Umfragen ist schnell und intuitiv.

Die Gruppen, welche in einem anderen System erstellt werden können, können für die Abstimmungen direkt verwendet werden. Alternativ ist auch ein Zugang über Link möglich, sodass Abstimmungen unabhängig von Gruppen sein können.

Import und Export von Terminabstimmungen/Umfragen ermöglicht einfaches Kopieren der Daten.

Sowohl Termine und Umfragen, als auch die Antworten können im Nachhinein noch geändert werden. Das Ergebnis einer Abstimmung liefert beispielsweise einen Termin, an welchem sich eine Gruppe treffen kann, wo die meisten Mitglieder Zeit haben.

Das Web-Element der Umfrage ist für bessere Übersicht, entsprechend den Entscheidungsmöglichkeiten, gefärbt. Die Farben sind so gewählt, dass sich Menschen mit Sehschwäche beser damit zurechtfinden.

=== Aufgabenstellung

[role="arc42help"]
****
.Inhalt
Kurzbeschreibung der fachlichen Aufgabenstellung, treibenden Kräfte, Extrakt (oder Abstract) der Anforderungen.
Verweis auf (hoffentlich vorliegende) Anforderungsdokumente (mit Versionsbezeichnungen und Ablageorten).

.Motivation
Aus Sicht der späteren Nutzung ist die Unterstützung einer fachlichen Aufgabe oder Verbesserung der Qualität der eigentliche Beweggrund, ein neues System zu schaffen oder ein bestehendes zu modifizieren.

.Form
Kurze textuelle Beschreibung, eventuell in tabellarischer Use-Case Form.
Sofern vorhanden, sollte die Aufgabenstellung Verweise auf die entsprechenden Anforderungsdokumente enthalten.

Halten Sie diese Auszüge so knapp wie möglich und wägen Sie Lesbarkeit und Redundanzfreiheit gegeneinander ab.
****

include::../anforderung.adoc[]

=== Qualitätsziele

[role="arc42help"]
****
.Inhalt
Die Top-3 bis Top-5 der Qualitätsziele für die Architektur, deren Erfüllung oder Einhaltung den maßgeblichen Stakeholdern besonders wichtig sind.
Gemeint sind hier wirklich Qualitätsziele, die nicht unbedingt mit den Zielen des Projekts übereinstimmen. Beachten Sie den Unterschied.

.Motivation
Weil Qualitätsziele grundlegende Architekturentscheidungen oft maßgeblich beeinflussen, sollten Sie die für Ihre Stakeholder relevanten Qualitätsziele kennen, möglichst konkret und operationalisierbar.

.Form
Tabellarische Darstellung der Qualitätsziele mit möglichst konkreten Szenarien, geordnet nach Prioritäten.
****

 * Schneller als Ilias 
 * Übersichtliches Desing und Funktion
 * Wartbarkeit

=== Stakeholder

[role="arc42help"]
****
.Inhalt
Expliziter Überblick über die Stakeholder des Systems – über alle Personen, Rollen oder Organisationen –, die

* die Architektur kennen sollten oder
* von der Architektur überzeugt werden müssen,
* mit der Architektur oder dem Code arbeiten (z.B. Schnittstellen nutzen),
* die Dokumentation der Architektur für ihre eigene Arbeit benötigen,
* Entscheidungen über das System und dessen Entwicklung treffen.

.Motivation
Sie sollten die Projektbeteiligten und -betroffenen kennen, sonst erleben Sie später im Entwicklungsprozess Überraschungen.
Diese Stakeholder bestimmen unter anderem Umfang und Detaillierungsgrad der von Ihnen zu leistenden Arbeit und Ergebnisse.

.Form
Tabelle mit Rollen- oder Personennamen, sowie deren Erwartungshaltung bezüglich der Architektur und deren Dokumentation.

[cols="1,1,2" options="header"]
|===
|Rolle |Kontakt |Erwartungshaltung
| _<Rolle-1>_ | _<Kontakt-1>_ | _<Erwartung-1>_
| _<Rolle-2>_ | _<Kontakt-2>_ | _<Erwartung-2>_ 
|===
****

[cols="1,1,2" options="header"]
|===
|Rolle |Kontakt |Erwartungshaltung
| _Organisatoren_ | _Jens_ | Es muss Multiuserfähig und schnell sein
| _Studenten_ |  | Intuitive Bedienung 
|===