[[section-design-decisions]]
== Entwurfsentscheidungen

[role="arc42help"]
****
.Inhalt
Wichtige, teure, große oder riskante Architektur- oder Entwurfsentscheidungen inklusive der jeweiligen Begründungen.
Mit "Entscheidungen" meinen wir hier die Auswahl einer von mehreren Alternativen unter vorgegebenen Kriterien.

Wägen Sie ab, inwiefern Sie Entscheidungen hier zentral beschreiben, oder wo eine lokale Beschreibung (z.B. in der Whitebox-Sicht von Bausteinen) sinnvoller ist.
Vermeiden Sie Redundanz.
Verweisen Sie evtl. auf Abschnitt 4, wo schon grundlegende strategische Entscheidungen beschrieben wurden.

.Motivation
Stakeholder des Systems sollten wichtige Entscheidungen verstehen und nachvollziehen können.

.Form
Verschiedene Möglichkeiten:

* Liste oder Tabelle, nach Wichtigkeit und Tragweite der Entscheidungen geordnet
* ausführlicher in Form einzelner Unterkapitel je Entscheidung
* ADR (http://thinkrelevance.com/blog/2011/11/15/documenting-architecture-decisions[Architecture Decision Record]) für jede wichtige Entscheidung
****

=== Wahl des Datenbankmodells

Wir haben uns dazu entschieden, viele Daten in einer Tabelle zu speichern und auch Redundanz zu erhalten, damit die Zugriffe sehr schnell erfolgen, wenige Joins gemacht werden müssen und somit keine große Latenz entsteht. Ein weiterer Vorteil war, dass die Objekte in der Geschäftslogik gut verwendet werden konnten.

=== Userinterface

Bei der Gestaltung des Userinterfaces war es uns wichtig, dass die relevanten Daten für den Nutzer schnell ersichtlich sind und insgesamt eine userfreundliche Benutzung ermöglicht wird. Auch die Möglichkeit nach Gruppen zu filtern soll es einfacher machen, Terminfindungen oder Umfragen nur für eine Gruppe zu sehen bzw. auch erstellen zu können. 

=== Database Initializer

Wir haben uns dazu entschieden, einen Database Initializer zu schreiben, damit wir bei Programmstart bereits Dummy-Daten in der Datenbank haben und somit einige Sachen anzeigen lassen können bzw. neue Terminfindungen und Umfragen einfacher erstellen können.

=== Schnittstelle zu Gruppenbildung

Anstatt die Objekte aus der Anfrage direkt zu übernehmen, haben wir die Entscheidung getroffen, eigene Objekte aus den erhaltenen Daten zu konstruieren. Der Vorteil für uns war der, dass wir nicht alle Daten benötigen und so direkt filtern konnten bzw. auch die Zugriffe auf die Gruppen wieder besser erfolgen können. 

=== Allgemeine Anmerkungen

Detailliertere Entscheidungen und Begründungen sind in unserer anderen Dokumentation für die jeweiligen Tage und Teile des Programms einsehbar.
